# Generated by Django 5.1.7 on 2025-04-04 19:24

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True)),
                ('phone', models.CharField(db_column='phone', max_length=9, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number with country code (e.g., 123456789).', regex='^\\d{9}$')])),
                ('first_name', models.CharField(db_column='first_name', max_length=30)),
                ('is_superuser', models.IntegerField(db_column='is_superuser', default=0)),
                ('is_staff', models.IntegerField(db_column='is_staff', default=0)),
                ('is_active', models.IntegerField(db_column='is_active', default=0)),
                ('last_name', models.CharField(db_column='last_name', max_length=30)),
                ('last_login', models.DateTimeField(db_column='last_login')),
                ('date_joined', models.DateTimeField(db_column='date_joined', default=datetime.date(2025, 4, 4))),
            ],
            options={
                'db_table': 'app_user',
            },
        ),
        migrations.CreateModel(
            name='Raports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raport_type', models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found')], max_length=5)),
                ('animal_type', models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog')], max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Raport',
                'verbose_name_plural': 'Raports',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='animal_images')),
                ('image_attributes', models.FileField(upload_to='animal_attributes', validators=[django.core.validators.FileExtensionValidator(['csv'])])),
                ('raport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.raports')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
