# Generated by Django 5.1.7 on 2025-03-23 13:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_raports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='animal_images')),
                ('image_attributes', models.FileField(upload_to='animal_attributes', validators=[django.core.validators.FileExtensionValidator(['csv'])])),
                ('raport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.raports')),
            ],
        ),
    ]
