# Generated by Django 5.1.7 on 2025-03-25 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='raports',
            options={'verbose_name': 'Raport', 'verbose_name_plural': 'Raports'},
        ),
    ]
