# Generated by Django 5.1.7 on 2025-04-11 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_raports_date_added_raports_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raports',
            options={},
        ),
        migrations.AlterField(
            model_name='raports',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='raports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='raports',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='raports',
            name='address',
            field=models.CharField(db_column='address', default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='IMG_Database/Cats'),
        ),
        migrations.AlterField(
            model_name='raports',
            name='animal_type',
            field=models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog')], db_column='animal_type', max_length=3),
        ),
        migrations.AlterField(
            model_name='raports',
            name='date_added',
            field=models.DateTimeField(db_column='date_added'),
        ),
        migrations.AlterField(
            model_name='raports',
            name='description',
            field=models.CharField(db_column='description', default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='raports',
            name='raport_type',
            field=models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found')], db_column='raport_type', max_length=5),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='date_joined',
            field=models.DateTimeField(db_column='date_joined'),
        ),
        migrations.AlterModelTable(
            name='raports',
            table='app_raports',
        ),
    ]
