# Generated by Django 5.1.7 on 2025-04-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_raports_options_alter_raports_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raports',
            name='id',
            field=models.BigAutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
