# Generated by Django 5.1.7 on 2025-04-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_raports_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image_attributes',
        ),
    ]
