# Generated by Django 5.1.7 on 2025-04-28 14:58

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_images_image_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raports',
            name='address',
        ),
        migrations.AddField(
            model_name='raports',
            name='district',
            field=models.CharField(db_column='district', default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='images',
            name='id',
            field=models.BigAutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(db_column='image', upload_to=app.models.numbered_upload_path),
        ),
        migrations.AlterField(
            model_name='images',
            name='raport',
            field=models.ForeignKey(db_column='raport_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.raports'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_active',
            field=models.IntegerField(db_column='is_active', default=1),
        ),
    ]
