# Generated by Django 5.1.7 on 2025-05-05 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_raports_address_raports_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(db_column='phone_number', max_length=9, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g., 123456789).', regex='^\\d{9}$')]),
        ),
    ]
