# Generated by Django 5.1.7 on 2025-05-05 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_usermodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='last_login',
            field=models.DateTimeField(db_column='last_login', default=django.utils.timezone.now),
        ),
    ]
