# Generated by Django 5.1.7 on 2025-05-05 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_usermodel_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='date_joined',
            field=models.DateTimeField(db_column='date_joined', default=django.utils.timezone.now),
        ),
    ]
