# Generated by Django 5.1.7 on 2025-06-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_usermodel_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
